Support app parameters
SAP-samples/btp-setup-automator pull request #345
Opened 2022-12-04 10:20 UTC by rui1610

This PR addresses the issue https://github.com/SAP-samples/btp-setup-automator/issues/313 so that required parameters for subscribing to apps are provided in the btpsa-usecase.json library.

2022-12-04 15:25 UTC, lechnerc77 requested changes
Something went wrong with the rebase/merge of your branch towards the `dev` branch. The availability to define labels to resources would be removed by your commit. 
This needs to be corrected before merging the pull request

2022-12-04 15:25 UTC, lechnerc77 commented on config/templates/libs/BTPSA-USECASE.json
> -                    "labels":{
The functionality of  labels are removed with your commit - there seems to be something wrong with the rebase/merge

2022-12-04 15:25 UTC, lechnerc77 commented on libs/btpsa-usecase.json
> -                    "labels":{
The functionality of labels are removed with your commit - there seems to be something wrong with the rebase/merge

2022-12-04 17:21 UTC, rui1610 commented
Great catch! Don't know what happened. I've just fixed the issue and it should be fine now. Would you mind checking again?

2022-12-05 07:16 UTC, lechnerc77 approved these changes

2022-12-05 07:17 UTC, merged