Fix broken links and usecase file update
SAP-samples/btp-setup-automator pull request #424
Opened 2023-02-08 15:24 UTC by maxstreifeneder

## Purpose
Fix to broken links and updates to the usecase file (replace mbt & cds scripts with npm commands since the app itself changed quite a bit) 

## Does the PR solve an issue

```
[x] Yes - #423 
[ ] No
```

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe: Broken Links in usecase file + docs to the resilient apps repo, additionally replaced mbt & cds commands with more "complex" npm scripts in the usecase file
```

## How to Test
integrationtest03.json should be enough

## What to Check

Verify that the following are valid
- MTAR file of the usecase file can still be deployed to a SAP BTP subaccount

2023-02-08 15:49 UTC, lechnerc77 requested changes
One reference must be adjusted I think

2023-02-08 15:49 UTC, lechnerc77 commented on tests/integrationtests/parameterfiles/integrationtest03.json
> +  "usecasefile": "https://raw.githubusercontent.com/maxstreifeneder/btp-setup-automator/main/usecases/released/build_resilient_apps_free_tier.json",
Should be `SAP-samples` I guess

2023-02-09 09:50 UTC, maxstreifeneder commented on tests/integrationtests/parameterfiles/integrationtest03.json
> +  "usecasefile": "https://raw.githubusercontent.com/maxstreifeneder/btp-setup-automator/main/usecases/released/build_resilient_apps_free_tier.json",
yep, you are right!

2023-02-09 14:49 UTC, lechnerc77 approved these changes

2023-02-09 14:49 UTC, merged